server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: beacon-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/beacons/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        - id: media-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/media/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**

        - id: sanctuary-map-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/map/**
