version: '3.8'
services:
  postgres-userdb:
    image: postgres:15
    container_name: userdb
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: userpass
    ports:
      - "5433:5432"
    volumes:
      - userdb_data:/var/lib/postgresql/data

volumes:
  userdb_data:
